    /*
     * To change this license header, choose License Headers in Project Properties.
     * To change this template file, choose Tools | Templates
     * and open the template in the editor.
     */
    package lk.ijse.royal_institute.views;
    
    import lk.ijse.royal_institute.controller.MainFormController;
    import lk.ijse.royal_institute.dto.CourseDTO;
    import lk.ijse.royal_institute.dto.RegistrationDTO;
    import lk.ijse.royal_institute.dto.StudentDTO;
    import lk.ijse.royal_institute.entity.QueryDTO;
    import org.hibernate.HibernateException;
    
    import javax.swing.*;
    import javax.swing.table.DefaultTableModel;
    import java.awt.event.ActionEvent;
    import java.awt.event.MouseEvent;
    import java.text.ParseException;
    import java.text.SimpleDateFormat;
    import java.util.ArrayList;
    import java.util.Date;
    import java.util.logging.Level;
    import java.util.logging.Logger;
    
    /**
     *
     * @author sandu
     */
    public class MainForm extends javax.swing.JFrame {
    
        /**
         * Creates new form MainForm
         */
        public MainForm() {
            initComponents();
            hideAllPanels();
            pnl1.setVisible(true);
            loadAllCourses();
            loadAllRegistrations();
        }
    
    
        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">
        private void initComponents() {
    
            buttonGroup1 = new javax.swing.ButtonGroup();
            pnlHeader = new javax.swing.JPanel();
            lblCompanyName = new javax.swing.JLabel();
            pnlNav = new javax.swing.JPanel();
            btnDetails = new javax.swing.JButton();
            btnStudents = new javax.swing.JButton();
            btnPrograms = new javax.swing.JButton();
            lrdPnlMain = new javax.swing.JLayeredPane();
            pnl3 = new javax.swing.JPanel();
            pnlRight2 = new javax.swing.JPanel();
            scrlPn2 = new javax.swing.JScrollPane();
            tblDetails = new javax.swing.JTable();
            pnl2 = new javax.swing.JPanel();
            pnlLeft1 = new javax.swing.JPanel();
            lblCourseCode = new javax.swing.JLabel();
            txtCourseCode = new javax.swing.JTextField();
            lblCourseName = new javax.swing.JLabel();
            lblType = new javax.swing.JLabel();
            txtCourseName = new javax.swing.JTextField();
            lblDuration = new javax.swing.JLabel();
            txtDuration = new javax.swing.JTextField();
            cmbBxType = new javax.swing.JComboBox<>();
            btnConfirm2 = new javax.swing.JButton();
            btnClear2 = new javax.swing.JButton();
            pnlRight1 = new javax.swing.JPanel();
            jScrollPane4 = new javax.swing.JScrollPane();
            tblCourses = new javax.swing.JTable();
            pnl1 = new javax.swing.JPanel();
            pnlLeft = new javax.swing.JPanel();
            lblStudentID = new javax.swing.JLabel();
            txtStudentID = new javax.swing.JTextField();
            lblStudentName = new javax.swing.JLabel();
            lblAddress = new javax.swing.JLabel();
            lblGender = new javax.swing.JLabel();
            txtStudentName = new javax.swing.JTextField();
            lblDOB = new javax.swing.JLabel();
            txtDOB = new javax.swing.JTextField();
            lblContactNo = new javax.swing.JLabel();
            txtContactNo = new javax.swing.JTextField();
            jScrollPane1 = new javax.swing.JScrollPane();
            txtAddress = new javax.swing.JTextArea();
            cmbBxGender = new javax.swing.JComboBox<>();
            pnlRight = new javax.swing.JPanel();
            lblRegDate = new javax.swing.JLabel();
            txtRegDate = new javax.swing.JTextField();
            lblRegNo = new javax.swing.JLabel();
            txtRegNo = new javax.swing.JTextField();
            txtRegFee = new javax.swing.JTextField();
            lblProgramID = new javax.swing.JLabel();
            cmbBxProgramID = new javax.swing.JComboBox<>();
            lblRegFee = new javax.swing.JLabel();
            btnClear1 = new javax.swing.JButton();
            btnConfirm1 = new javax.swing.JButton();
    
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Royal Institute - Student Registration");
            setMinimumSize(new java.awt.Dimension(840, 580));
            setPreferredSize(new java.awt.Dimension(845, 600));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            pnlHeader.setBackground(new java.awt.Color(255, 255, 255));
            pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            lblCompanyName.setBackground(new java.awt.Color(255, 255, 255));
            lblCompanyName.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 20)); // NOI18N
            lblCompanyName.setForeground(new java.awt.Color(0, 0, 0));
            lblCompanyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblCompanyName.setText("Royal Institute - Student Registration");
            pnlHeader.add(lblCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 60));
    
            getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 60));
    
            pnlNav.setBackground(new java.awt.Color(255, 255, 255));
            pnlNav.setForeground(new java.awt.Color(204, 204, 204));
            pnlNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            btnDetails.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
            btnDetails.setForeground(new java.awt.Color(102, 102, 102));
            btnDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("assets/list_28px.png"))); // NOI18N
            btnDetails.setText("Details");
            btnDetails.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDetailsActionPerformed(evt);
                }
            });
            pnlNav.add(btnDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 200, 50));
    
            btnStudents.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
            btnStudents.setForeground(new java.awt.Color(102, 102, 102));
            btnStudents.setIcon(new javax.swing.ImageIcon(getClass().getResource("assets/student_male_28px.png"))); // NOI18N
            btnStudents.setText("Students");
            btnStudents.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnStudentsActionPerformed(evt);
                }
            });
            pnlNav.add(btnStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 200, 50));
    
            btnPrograms.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 16)); // NOI18N
            btnPrograms.setForeground(new java.awt.Color(102, 102, 102));
            btnPrograms.setIcon(new javax.swing.ImageIcon(getClass().getResource("assets/study_28px.png"))); // NOI18N
            btnPrograms.setText("Programs");
            btnPrograms.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnProgramsActionPerformed(evt);
                }
            });
            pnlNav.add(btnPrograms, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 200, 50));
    
            getContentPane().add(pnlNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 810, 90));
    
            lrdPnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            pnlRight2.setBackground(new java.awt.Color(255, 255, 255));
            pnlRight2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            tblDetails.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
                            {null, null, null, null, null, null, null},
                            {null, null, null, null, null, null, null},
                            {null, null, null, null, null, null, null},
                            {null, null, null, null, null, null, null}
                    },
                    new String [] {
                            "Reg No", "Reg Date", "Reg Fee", "Course Code", "Course Name", "Student ID", "Student Name"
                    }
            ) {
                boolean[] canEdit = new boolean [] {
                        false, false, false, false, false, false, true
                };
    
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
    
            scrlPn2.setViewportView(tblDetails);
    
            pnlRight2.add(scrlPn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 350));
    
            pnl3.add(pnlRight2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));
    
            lrdPnlMain.add(pnl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));
    
            pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            pnlLeft1.setBackground(new java.awt.Color(255, 255, 255));
            pnlLeft1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            lblCourseCode.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblCourseCode.setForeground(new java.awt.Color(0, 0, 0));
            lblCourseCode.setText("Course Code :");
            pnlLeft1.add(lblCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));
            pnlLeft1.add(txtCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 30));
    
            lblCourseName.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblCourseName.setForeground(new java.awt.Color(0, 0, 0));
            lblCourseName.setText("Name :");
            pnlLeft1.add(lblCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));
    
            lblType.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblType.setForeground(new java.awt.Color(0, 0, 0));
            lblType.setText("Type :");
            pnlLeft1.add(lblType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));
            pnlLeft1.add(txtCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 260, 30));
    
            lblDuration.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblDuration.setForeground(new java.awt.Color(0, 0, 0));
            lblDuration.setText("Duration :");
            pnlLeft1.add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));
            pnlLeft1.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 30));
    
            cmbBxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full-Time", "Part-Time" }));
            cmbBxType.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbBxTypeActionPerformed(evt);
                }
            });
            pnlLeft1.add(cmbBxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, 30));
    
            btnConfirm2.setBackground(new java.awt.Color(46, 204, 113));
            btnConfirm2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
            btnConfirm2.setText("Confirm");
            btnConfirm2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConfirm2ActionPerformed(evt);
                }
            });
            pnlLeft1.add(btnConfirm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 120, 40));
    
            btnClear2.setBackground(new java.awt.Color(231, 76, 60));
            btnClear2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
            btnClear2.setText("Clear");
            btnClear2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnClear2ActionPerformed(evt);
                }
            });
            pnlLeft1.add(btnClear2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 120, 40));
    
            pnl2.add(pnlLeft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));
    
            pnlRight1.setBackground(new java.awt.Color(255, 255, 255));
            pnlRight1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            tblCourses.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
            tblCourses.setModel(new javax.swing.table.DefaultTableModel(
                    new Object [][] {
    
                    },
                    new String [] {
                            "Code", "Name", "Type", "Duration"
                    }
            ) {
                boolean[] canEdit = new boolean [] {
                        false, false, false, false
                };
    
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane4.setViewportView(tblCourses);
    
            pnlRight1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 350));
    
            pnl2.add(pnlRight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 400, 370));
    
            lrdPnlMain.add(pnl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));
    
            pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
            pnlLeft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            lblStudentID.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblStudentID.setForeground(new java.awt.Color(0, 0, 0));
            lblStudentID.setText("Student ID :");
            pnlLeft.add(lblStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));
            pnlLeft.add(txtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 170, 30));
    
            lblStudentName.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblStudentName.setForeground(new java.awt.Color(0, 0, 0));
            lblStudentName.setText("Name :");
            pnlLeft.add(lblStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));
    
            lblAddress.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblAddress.setForeground(new java.awt.Color(0, 0, 0));
            lblAddress.setText("Address :");
            pnlLeft.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));
    
            lblGender.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblGender.setForeground(new java.awt.Color(0, 0, 0));
            lblGender.setText("Gender :");
            pnlLeft.add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 100, 30));
            pnlLeft.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 260, 30));
    
            lblDOB.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblDOB.setForeground(new java.awt.Color(0, 0, 0));
            lblDOB.setText("DOB :");
            pnlLeft.add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 30));
            txtDOB.setText("DD-MM-YYYY");
            pnlLeft.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 30));
    
            lblContactNo.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblContactNo.setForeground(new java.awt.Color(0, 0, 0));
            lblContactNo.setText("Contact No :");
            pnlLeft.add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 30));
            pnlLeft.add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 30));
    
            txtAddress.setColumns(20);
            txtAddress.setRows(5);
            jScrollPane1.setViewportView(txtAddress);
    
            pnlLeft.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 260, 80));
    
            cmbBxGender.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
            cmbBxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
            pnlLeft.add(cmbBxGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, 30));
    
            pnl1.add(pnlLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 370));
    
            pnlRight.setBackground(new java.awt.Color(255, 255, 255));
            pnlRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
    
            lblRegDate.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblRegDate.setForeground(new java.awt.Color(0, 0, 0));
            lblRegDate.setText("Reg Date :");
            txtRegDate.setText("DD-MM-YYYY");
            pnlRight.add(lblRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 100, 30));
            pnlRight.add(txtRegDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 260, 30));
    
            lblRegNo.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblRegNo.setForeground(new java.awt.Color(0, 0, 0));
            lblRegNo.setText("Reg No :");
            pnlRight.add(lblRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 30));
            pnlRight.add(txtRegNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 260, 30));
            pnlRight.add(txtRegFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 260, 30));
    
            lblProgramID.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblProgramID.setForeground(new java.awt.Color(0, 0, 0));
            lblProgramID.setText("Program ID :");
            pnlRight.add(lblProgramID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 30));
    
            cmbBxProgramID.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
            cmbBxProgramID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CT0301", "CT0402", "CT0330", "CT0545", "CT0412" }));
            cmbBxProgramID.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    cmbBxProgramIDActionPerformed(evt);
                }
            });
            pnlRight.add(cmbBxProgramID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 260, 30));
    
            lblRegFee.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
            lblRegFee.setForeground(new java.awt.Color(0, 0, 0));
            lblRegFee.setText("Reg Fee :");
            pnlRight.add(lblRegFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 30));
    
            btnClear1.setBackground(new java.awt.Color(231, 76, 60));
            btnClear1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
            btnClear1.setText("Clear");
            btnClear1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnClear1ActionPerformed(evt);
                }
            });
            pnlRight.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, 40));
    
            btnConfirm1.setBackground(new java.awt.Color(46, 204, 113));
            btnConfirm1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
            btnConfirm1.setText("Confirm");
            btnConfirm1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnConfirm1ActionPerformed(evt);
                }
            });
            pnlRight.add(btnConfirm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 120, 40));
    
            pnl1.add(pnlRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 400, 280));
    
            lrdPnlMain.add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 370));
    
            getContentPane().add(lrdPnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 810, -1));
    
            pack();
        }// </editor-fold>
    
        private void btnConfirm1ActionPerformed(ActionEvent evt) {
            String studentID=txtStudentID.getText();
            String studentName=txtStudentName.getText();
            String address=txtAddress.getText();
            String contactNo=txtContactNo.getText();
            String gender=cmbBxGender.getSelectedItem().toString();
            Date dob=null;
            try {
                dob=new SimpleDateFormat("dd-mm-yyyy").parse(txtDOB.getText());
            } catch (ParseException e) {
                e.printStackTrace();
            }
            String regNo=txtRegNo.getText();
            Date regDate=null;
            try {
                regDate=new SimpleDateFormat("dd-mm-yyyy").parse(txtRegDate.getText());
            } catch (ParseException e) {
                e.printStackTrace();
            }
            double regFee=Double.parseDouble(txtRegFee.getText());
            String programID=cmbBxProgramID.getSelectedItem().toString();
    
    
    
            try {
                RegistrationDTO newRegistration = new RegistrationDTO(regNo,regDate,regFee,
                        new StudentDTO(studentID,studentName,address,contactNo,dob,gender),
                        new CourseDTO(programID,"","",""));
                boolean addRegistration = new MainFormController().addRegistration(newRegistration);
                if (addRegistration) {
                    JOptionPane.showMessageDialog(this, "Student added and registered to course.");
                    clearAll();
                    loadAllRegistrations();
                } else {
                    JOptionPane.showMessageDialog(this, "Student not registered..!");
                }
    
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HibernateException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    
        }
    
        private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            hideAllPanels();
            pnl3.setVisible(true);
        }
    
        private void btnStudentsActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            hideAllPanels();
            pnl1.setVisible(true);
        }
    
        private void btnProgramsActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            hideAllPanels();
            pnl2.setVisible(true);
        }
    
        private void cmbBxTypeActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
    
        private void cmbBxProgramIDActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }
    
        private void btnConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            String courseCode=txtCourseCode.getText();
            String courseName=txtCourseName.getText();
            String type=cmbBxType.getSelectedItem().toString();
            String duration=txtDuration.getText();
    
            try {
                CourseDTO newCourse = new CourseDTO(courseCode, courseName, type, duration);
                boolean addCourse = new MainFormController().addCourse(newCourse);
                if (addCourse) {
                    JOptionPane.showMessageDialog(this, "Course registered..!");
                    clearAll();
                    loadAllCourses();
                } else {
                    JOptionPane.showMessageDialog(this, "Course not registered..!");
                }
    
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HibernateException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    
    
    
    
        }
    
        private void loadAllCourses() {
            DefaultTableModel dtm = (DefaultTableModel) tblCourses.getModel();
            dtm.setRowCount(0);
    
            try {
                ArrayList<CourseDTO> allCourses = new MainFormController().getAllCourses();
                for (CourseDTO c : allCourses) {
    
                    Object[] row = {c.getCourseCode(),c.getCourseName(),c.getCourseType(),c.getDuration()};
                    dtm.addRow(row);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HibernateException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    
        }
    
    
        private void loadAllRegistrations() {
            DefaultTableModel dtm = (DefaultTableModel) tblDetails.getModel();
            dtm.setRowCount(0);
    
            try {
                ArrayList<QueryDTO> allRegistrations = new MainFormController().getAllRegistrations();
                for (QueryDTO q : allRegistrations) {
    
                    Object[] row = {q.getRegNo(),q.getRegDate(),q.getRegFee(),q.getCourseCode(),q.getCourseName(),q.getStudentID(),q.getStudentName()};
                    dtm.addRow(row);
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (HibernateException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
    
        }
    
        private void btnClear2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            clearAll();
        }
    
        private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            clearAll();
        }
    
        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>
    
            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new MainForm().setVisible(true);
                }
            });
        }
    
        // Variables declaration - do not modify
        private javax.swing.JButton btnClear1;
        private javax.swing.JButton btnClear2;
        private javax.swing.JButton btnConfirm1;
        private javax.swing.JButton btnConfirm2;
        private javax.swing.JButton btnDetails;
        private javax.swing.JButton btnPrograms;
        private javax.swing.JButton btnStudents;
        private javax.swing.ButtonGroup buttonGroup1;
        private javax.swing.JComboBox<String> cmbBxProgramID;
        private javax.swing.JComboBox<String> cmbBxType;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JLabel lblAddress;
        private javax.swing.JLabel lblCourseCode;
        private javax.swing.JLabel lblCompanyName;
        private javax.swing.JLabel lblContactNo;
        private javax.swing.JLabel lblCourseName;
        private javax.swing.JLabel lblDOB;
        private javax.swing.JLabel lblDuration;
        private javax.swing.JLabel lblGender;
        private javax.swing.JLabel lblProgramID;
        private javax.swing.JLabel lblRegDate;
        private javax.swing.JLabel lblRegFee;
        private javax.swing.JLabel lblRegNo;
        private javax.swing.JLabel lblStudentID;
        private javax.swing.JLabel lblStudentName;
        private javax.swing.JLabel lblType;
        private javax.swing.JLayeredPane lrdPnlMain;
        private javax.swing.JPanel pnl1;
        private javax.swing.JPanel pnl2;
        private javax.swing.JPanel pnl3;
        private javax.swing.JPanel pnlHeader;
        private javax.swing.JPanel pnlLeft;
        private javax.swing.JPanel pnlLeft1;
        private javax.swing.JPanel pnlNav;
        private javax.swing.JPanel pnlRight;
        private javax.swing.JPanel pnlRight1;
        private javax.swing.JPanel pnlRight2;
        private javax.swing.JScrollPane scrlPn2;
        private javax.swing.JTable tblCourses;
        private javax.swing.JTable tblDetails;
        private javax.swing.JTextArea txtAddress;
        private javax.swing.JTextField txtContactNo;
        private javax.swing.JTextField txtCourseCode;
        private javax.swing.JTextField txtCourseName;
        private javax.swing.JTextField txtDOB;
        private javax.swing.JTextField txtDuration;
        private javax.swing.JComboBox<String> cmbBxGender;
        private javax.swing.JTextField txtRegDate;
        private javax.swing.JTextField txtRegFee;
        private javax.swing.JTextField txtRegNo;
        private javax.swing.JTextField txtStudentID;
        private javax.swing.JTextField txtStudentName;
        // End of variables declaration
    
        private void hideAllPanels() {
            pnl1.setVisible(false);
            pnl2.setVisible(false);
            pnl3.setVisible(false);
        }
    
        private void clearAll() {
            txtCourseCode.setText("");
            txtCourseName.setText("");
            cmbBxType.setSelectedIndex(0);
            txtDuration.setText("");
    
            txtStudentID.setText("");
            txtStudentName.setText("");
            txtAddress.setText("");
            txtContactNo.setText("");
    
            cmbBxGender.setSelectedIndex(0);
            txtRegNo.setText("");
    
            txtRegFee.setText("");
            cmbBxProgramID.setSelectedIndex(0);
    
    
            txtDOB.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtDOBMouseClicked(evt);
                }
            });
    
            txtRegDate.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    txtRegDateMouseClicked(evt);
                }
            });
    
        }
    
        private void txtRegDateMouseClicked(MouseEvent evt) {
            txtRegDate.setText("");
        }
    
        private void txtDOBMouseClicked(MouseEvent evt) {
            txtDOB.setText("");
        }
    }
